spring:
  datasource:
    url: jdbc:p6spy:sqlite:D:/workspace/update/src/main/resources/db/db.sqlite
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username:
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      mode: always
      continue-on-error: true
jar: 
  list: CEEJB, CEWebService, com.cs.core.xml, Core, CSBase, ProjectJARs